version: "3.3"
services:
  nginx:
    build: ./nginx
    volumes:
      - ./static:/usr/share/nginx/html/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  gunicorn:
    build: ./gunicorn
    volumes:
      - ./app:/app
      - ./static:/static
      - ./static/files:/app/files
    restart: always
    depends_on:
      - postgres
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
  postgres:
    image: postgres
    volumes:
        # - ./postgres_data:/var/lib/postgresql/data
        # Yes, this is a fix ..
      - ./postgres_data:/var/lib/postgresql/enodata
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    # user: 1000:1000
    environment:
      POSTGRES_PASSWORD: example
